[[plugins]]
  package = "@netlify/plugin-nextjs"

[build]
  command = "npx prisma generate && next build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"
  NODE_VERSION = "18"
